/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description 注册成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                token: string;
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    name: string;
                                    /** @enum {string} */
                                    role?: "USER" | "ADMIN";
                                    /** Format: date-time */
                                    createdAt?: string;
                                };
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                token: string;
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    name: string;
                                    /** @enum {string} */
                                    role?: "USER" | "ADMIN";
                                    /** Format: date-time */
                                    createdAt?: string;
                                };
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 书籍列表 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    status?: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                    categoryId?: string;
                    sortBy?: "createdAt" | "title" | "author" | "pageCount";
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 书籍分页列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                items: {
                                    /**
                                     * Format: uuid
                                     * @example 4e8311a0-8f32-4e9d-a17b-0e9f12345678
                                     */
                                    id: string;
                                    /** @example Clean Code */
                                    title: string;
                                    /** @example Robert C. Martin */
                                    author: string;
                                    isbn?: string | null;
                                    publishedDate?: string | null;
                                    pageCount?: number | null;
                                    description?: string | null;
                                    coverUrl?: string | null;
                                    /** @enum {string} */
                                    status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                                    /** Format: uuid */
                                    categoryId?: string | null;
                                    /** Format: uuid */
                                    userId: string;
                                    /** Format: date-time */
                                    createdAt: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                                totalPages: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建书籍 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        author: string;
                        isbn?: string;
                        publishedDate?: string;
                        pageCount?: number;
                        description?: string;
                        /** Format: uri */
                        coverUrl?: string;
                        /**
                         * @default WISHLIST
                         * @enum {string}
                         */
                        status?: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                        /** Format: uuid */
                        categoryId?: string;
                    };
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                /**
                                 * Format: uuid
                                 * @example 4e8311a0-8f32-4e9d-a17b-0e9f12345678
                                 */
                                id: string;
                                /** @example Clean Code */
                                title: string;
                                /** @example Robert C. Martin */
                                author: string;
                                isbn?: string | null;
                                publishedDate?: string | null;
                                pageCount?: number | null;
                                description?: string | null;
                                coverUrl?: string | null;
                                /** @enum {string} */
                                status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                                /** Format: uuid */
                                categoryId?: string | null;
                                /** Format: uuid */
                                userId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新书籍 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                        author?: string;
                        isbn?: string;
                        publishedDate?: string;
                        pageCount?: number;
                        description?: string;
                        /** Format: uri */
                        coverUrl?: string;
                        /**
                         * @default WISHLIST
                         * @enum {string}
                         */
                        status?: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                        /** Format: uuid */
                        categoryId?: string;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                /**
                                 * Format: uuid
                                 * @example 4e8311a0-8f32-4e9d-a17b-0e9f12345678
                                 */
                                id: string;
                                /** @example Clean Code */
                                title: string;
                                /** @example Robert C. Martin */
                                author: string;
                                isbn?: string | null;
                                publishedDate?: string | null;
                                pageCount?: number | null;
                                description?: string | null;
                                coverUrl?: string | null;
                                /** @enum {string} */
                                status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                                /** Format: uuid */
                                categoryId?: string | null;
                                /** Format: uuid */
                                userId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        /** 删除书籍 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分类列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 分类列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                color: string;
                                /** Format: uuid */
                                userId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建分类 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        color: string;
                    };
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                color: string;
                                /** Format: uuid */
                                userId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{bookId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建评论 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bookId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        rating: number;
                        text?: string;
                    };
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            message: string;
                            data: {
                                /** Format: uuid */
                                id: string;
                                rating: number;
                                text?: string | null;
                                /** Format: uuid */
                                bookId: string;
                                /** Format: uuid */
                                userId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Book: {
            /**
             * Format: uuid
             * @example 4e8311a0-8f32-4e9d-a17b-0e9f12345678
             */
            id: string;
            /** @example Clean Code */
            title: string;
            /** @example Robert C. Martin */
            author: string;
            isbn?: string | null;
            publishedDate?: string | null;
            pageCount?: number | null;
            description?: string | null;
            coverUrl?: string | null;
            /** @enum {string} */
            status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            userId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateBookBody: {
            title: string;
            author: string;
            isbn?: string;
            publishedDate?: string;
            pageCount?: number;
            description?: string;
            /** Format: uri */
            coverUrl?: string;
            /**
             * @default WISHLIST
             * @enum {string}
             */
            status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
            /** Format: uuid */
            categoryId?: string;
        };
        UpdateBookBody: {
            title?: string;
            author?: string;
            isbn?: string;
            publishedDate?: string;
            pageCount?: number;
            description?: string;
            /** Format: uri */
            coverUrl?: string;
            /**
             * @default WISHLIST
             * @enum {string}
             */
            status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
            /** Format: uuid */
            categoryId?: string;
        };
        ListBooksQuery: {
            /** @default 1 */
            page: number;
            /** @default 10 */
            pageSize: number;
            /** @enum {string} */
            status?: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
            /** Format: uuid */
            categoryId?: string;
            /**
             * @default createdAt
             * @enum {string}
             */
            sortBy: "createdAt" | "title" | "author" | "pageCount";
            /**
             * @default desc
             * @enum {string}
             */
            sortOrder: "asc" | "desc";
        };
        LoginBody: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterBody: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
        };
        AuthResponse: {
            token: string;
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                name: string;
                /** @enum {string} */
                role?: "USER" | "ADMIN";
                /** Format: date-time */
                createdAt?: string;
            };
        };
        ErrorResponse: {
            code: number;
            message: string;
            details?: unknown;
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
            /** Format: uuid */
            userId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateCategoryBody: {
            name: string;
            color: string;
        };
        UpdateCategoryBody: {
            name?: string;
            color?: string;
        };
        Review: {
            /** Format: uuid */
            id: string;
            rating: number;
            text?: string | null;
            /** Format: uuid */
            bookId: string;
            /** Format: uuid */
            userId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateReviewBody: {
            rating: number;
            text?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
